# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 5                       # Numero di link mostrati nel menu di navigazione
    default_options:
        page_name: page                 # Nome del parametro per il numero di pagina
        sort_field_name: sort           # Nome del parametro per il campo di ordinamento
        sort_direction_name: direction  # Nome del parametro per la direzione dell'ordinamento
        distinct: true                  # Imposta risultati distinti (utile per query con GROUP BY)
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' # Template per Bootstrap
